import type {
  AutoGenerateContractClause,
  AutoGenerateContractPayload,
  ContractBlueprintContext,
  LegalBlueprintQueryParams,
  LegalClauseMode,
  LegalContractModel,
  LegalIpMode,
  LegalRiskLevel,
  LegalSupportLevel,
  LegalWarningSeverity,
} from "@/types/legal-contracts";
import { normalizeCpfCnpjForSubmit } from "./cpf-cnpj";

export const LEGAL_AUDIENCE_OPTIONS: Array<{ value: "b2b" | "b2c"; label: string }> = [
  { value: "b2b", label: "Empresa para empresa" },
  { value: "b2c", label: "Empresa para consumidor" },
];

export const LEGAL_RISK_LEVEL_OPTIONS: Array<{ value: LegalRiskLevel; label: string }> = [
  { value: "baixo", label: "Baixo" },
  { value: "medio", label: "Medio" },
  { value: "alto", label: "Alto" },
];

export const LEGAL_CONTRACT_MODEL_OPTIONS: Array<{ value: LegalContractModel; label: string }> = [
  { value: "saas", label: "SaaS" },
  { value: "projeto", label: "Projeto" },
  { value: "servico_continuado", label: "Servico continuado" },
];

export const LEGAL_IP_MODE_OPTIONS: Array<{ value: LegalIpMode; label: string }> = [
  { value: "licenca", label: "Licenca de uso" },
  { value: "cessao", label: "Cessao integral" },
  { value: "titularidade_prestador", label: "Titularidade do prestador" },
];

export const LEGAL_SUPPORT_LEVEL_OPTIONS: Array<{ value: LegalSupportLevel; label: string }> = [
  { value: "none", label: "Sem suporte" },
  { value: "horario_comercial", label: "Horario comercial" },
  { value: "estendido", label: "Suporte estendido" },
];

export const PARTY_QUALIFICATION_FIELDS: Array<{
  key: "providerDocument" | "providerAddress" | "clientDocument" | "clientAddress";
  label: string;
  helperText: string;
  placeholder: string;
  multiline?: boolean;
}> = [
  {
    key: "providerDocument",
    label: "CNPJ da contratada",
    helperText: "Documento da empresa que emite o contrato.",
    placeholder: "Ex.: 12.345.678/0001-90",
  },
  {
    key: "providerAddress",
    label: "Endereco da contratada",
    helperText: "Endereco usado na qualificacao do contrato.",
    placeholder: "Ex.: Rua Exemplo, 100, Sao Paulo/SP",
    multiline: true,
  },
  {
    key: "clientDocument",
    label: "CPF/CNPJ do cliente",
    helperText: "Documento do cliente ou da empresa cliente.",
    placeholder: "Ex.: 123.456.789-00",
  },
  {
    key: "clientAddress",
    label: "Endereco do cliente",
    helperText: "Endereco do cliente no contrato.",
    placeholder: "Ex.: Av. Cliente, 200, Rio de Janeiro/RJ",
    multiline: true,
  },
];

export const LEGAL_CLAUSE_COMPLETENESS_OPTIONS: Array<{
  value: Exclude<LegalClauseMode, "custom">;
  label: string;
  range: string;
  targetClauseCount: number;
  description: string;
}> = [
  {
    value: "essential",
    label: "Enxuto",
    range: "Ate 8 clausulas",
    targetClauseCount: 8,
    description: "Contrato mais curto, com apenas as clausulas indispensaveis.",
  },
  {
    value: "balanced",
    label: "Padrao",
    range: "Ate 12 clausulas",
    targetClauseCount: 12,
    description: "Boa cobertura sem deixar o contrato pesado.",
  },
  {
    value: "complete",
    label: "Completo",
    range: "Ate 20 clausulas",
    targetClauseCount: 20,
    description: "Mais protecao para risco, recorrencia, dados ou IP.",
  },
  {
    value: "robust",
    label: "Robusto",
    range: "Ate 30+ clausulas",
    targetClauseCount: 30,
    description: "Cobertura ampla para maior valor ou maior exposicao.",
  },
];

export const CUSTOM_CLAUSE_COUNT_OPTIONS = [6, 12, 20, 30] as const;
export const DEFAULT_CLAUSE_MODE: LegalClauseMode = "balanced";
export const DEFAULT_TARGET_CLAUSE_COUNT = 12;

export const LEGAL_WARNING_LABELS: Record<LegalWarningSeverity, string> = {
  info: "Informativo",
  warning: "Atencao",
  critical: "Critico",
};

export function parseAuthenticationMethodsInput(value: string): string[] {
  return value
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

export function sortAutoGeneratedClauses<T extends AutoGenerateContractClause>(clauses: T[]): T[] {
  return [...clauses].sort((a, b) => a.orderIndex - b.orderIndex);
}

export function buildLegalBlueprintParams(
  context: AutoGenerateContractPayload,
): LegalBlueprintQueryParams {
  const params: LegalBlueprintQueryParams = {};

  if (context.audience) params.audience = context.audience;
  if (context.riskLevel) params.riskLevel = context.riskLevel;
  if (context.contractModels?.length) params.contractModels = context.contractModels.join(",");
  if (typeof context.personalData === "boolean") params.personalData = String(context.personalData) as "true" | "false";
  if (typeof context.sensitiveData === "boolean") params.sensitiveData = String(context.sensitiveData) as "true" | "false";
  if (typeof context.sourceCodeDelivery === "boolean") {
    params.sourceCodeDelivery = String(context.sourceCodeDelivery) as "true" | "false";
  }

  return params;
}

export function deriveContractModelsFromContractType(contractType?: string): LegalContractModel[] {
  if (contractType === "desenvolvimento" || contractType === "design") {
    return ["projeto"];
  }

  if (contractType === "marketing" || contractType === "consultoria") {
    return ["servico_continuado"];
  }

  return [];
}

export function mergeBlueprintDefaults(
  current: AutoGenerateContractPayload,
  defaults?: ContractBlueprintContext,
  contractType?: string,
): AutoGenerateContractPayload {
  const merged: AutoGenerateContractPayload = { ...current };
  const fallbackModels = deriveContractModelsFromContractType(contractType);

  if (!merged.audience && defaults?.audience) merged.audience = defaults.audience;
  if (!merged.riskLevel && defaults?.riskLevel) merged.riskLevel = defaults.riskLevel;

  if (!merged.contractModels?.length) {
    if (defaults?.contractModels?.length) merged.contractModels = [...defaults.contractModels];
    else if (fallbackModels.length) merged.contractModels = fallbackModels;
  }

  if (typeof merged.personalData !== "boolean" && typeof defaults?.personalData === "boolean") {
    merged.personalData = defaults.personalData;
  }
  if (typeof merged.sensitiveData !== "boolean" && typeof defaults?.sensitiveData === "boolean") {
    merged.sensitiveData = defaults.sensitiveData;
  }
  if (typeof merged.sourceCodeDelivery !== "boolean" && typeof defaults?.sourceCodeDelivery === "boolean") {
    merged.sourceCodeDelivery = defaults.sourceCodeDelivery;
  }
  if (!merged.ipMode && defaults?.ipMode) merged.ipMode = defaults.ipMode;
  if (!merged.supportLevel && defaults?.supportLevel) merged.supportLevel = defaults.supportLevel;
  if (typeof merged.subscription !== "boolean" && typeof defaults?.subscription === "boolean") {
    merged.subscription = defaults.subscription;
  }
  if (typeof merged.milestoneBilling !== "boolean" && typeof defaults?.milestoneBilling === "boolean") {
    merged.milestoneBilling = defaults.milestoneBilling;
  }
  if (typeof merged.includeArbitration !== "boolean" && typeof defaults?.includeArbitration === "boolean") {
    merged.includeArbitration = defaults.includeArbitration;
  }
  if (typeof merged.includeEscrow !== "boolean" && typeof defaults?.includeEscrow === "boolean") {
    merged.includeEscrow = defaults.includeEscrow;
  }
  if (typeof merged.includePortfolioUse !== "boolean" && typeof defaults?.includePortfolioUse === "boolean") {
    merged.includePortfolioUse = defaults.includePortfolioUse;
  }
  if (typeof merged.includeChargebackRule !== "boolean" && typeof defaults?.includeChargebackRule === "boolean") {
    merged.includeChargebackRule = defaults.includeChargebackRule;
  }
  if (typeof merged.includeHandOver !== "boolean" && typeof defaults?.includeHandOver === "boolean") {
    merged.includeHandOver = defaults.includeHandOver;
  }
  if (!merged.authenticationMethods?.length && defaults?.authenticationMethods?.length) {
    merged.authenticationMethods = [...defaults.authenticationMethods];
  }
  if (!merged.providerDocument && defaults?.providerDocument) merged.providerDocument = defaults.providerDocument;
  if (!merged.providerAddress && defaults?.providerAddress) merged.providerAddress = defaults.providerAddress;
  if (!merged.clientDocument && defaults?.clientDocument) merged.clientDocument = defaults.clientDocument;
  if (!merged.clientAddress && defaults?.clientAddress) merged.clientAddress = defaults.clientAddress;
  if (!merged.forumCityUf && defaults?.forumCityUf) merged.forumCityUf = defaults.forumCityUf;
  if (!merged.forumConnection && defaults?.forumConnection) merged.forumConnection = defaults.forumConnection;
  if (!merged.supportSummary && defaults?.supportSummary) merged.supportSummary = defaults.supportSummary;
  if (!merged.subprocessorSummary && defaults?.subprocessorSummary) {
    merged.subprocessorSummary = defaults.subprocessorSummary;
  }
  if (!merged.securitySummary && defaults?.securitySummary) merged.securitySummary = defaults.securitySummary;
  if (!merged.clauseMode && defaults?.clauseMode) merged.clauseMode = defaults.clauseMode;
  if (!merged.targetClauseCount && typeof defaults?.targetClauseCount === "number") {
    merged.targetClauseCount = defaults.targetClauseCount;
  }
  if (typeof merged.replaceExisting !== "boolean" && typeof defaults?.replaceExisting === "boolean") {
    merged.replaceExisting = defaults.replaceExisting;
  }

  return merged;
}

export function normalizeAutoGeneratePayload(
  context: AutoGenerateContractPayload,
  authenticationMethodsInput?: string,
): AutoGenerateContractPayload {
  const payload: AutoGenerateContractPayload = {
    ...context,
    authenticationMethods: authenticationMethodsInput !== undefined
      ? parseAuthenticationMethodsInput(authenticationMethodsInput)
      : context.authenticationMethods,
  };

  if (!payload.contractModels?.length) delete payload.contractModels;
  if (!payload.authenticationMethods?.length) delete payload.authenticationMethods;
  if (!payload.providerDocument?.trim()) delete payload.providerDocument;
  else payload.providerDocument = normalizeCpfCnpjForSubmit(payload.providerDocument, "Documento da contratada");
  if (!payload.providerAddress?.trim()) delete payload.providerAddress;
  else payload.providerAddress = payload.providerAddress.trim();
  if (!payload.clientDocument?.trim()) delete payload.clientDocument;
  else payload.clientDocument = normalizeCpfCnpjForSubmit(payload.clientDocument, "Documento do contratante");
  if (!payload.clientAddress?.trim()) delete payload.clientAddress;
  else payload.clientAddress = payload.clientAddress.trim();
  if (!payload.forumCityUf?.trim()) delete payload.forumCityUf;
  else payload.forumCityUf = payload.forumCityUf.trim();
  if (!payload.forumConnection?.trim()) delete payload.forumConnection;
  else payload.forumConnection = payload.forumConnection.trim();
  if (!payload.supportSummary?.trim()) delete payload.supportSummary;
  else payload.supportSummary = payload.supportSummary.trim();
  if (!payload.subprocessorSummary?.trim()) delete payload.subprocessorSummary;
  else payload.subprocessorSummary = payload.subprocessorSummary.trim();
  if (!payload.securitySummary?.trim()) delete payload.securitySummary;
  else payload.securitySummary = payload.securitySummary.trim();

  if (!payload.clauseMode) payload.clauseMode = DEFAULT_CLAUSE_MODE;
  if (typeof payload.targetClauseCount !== "number") {
    payload.targetClauseCount = payload.clauseMode === "custom"
      ? DEFAULT_TARGET_CLAUSE_COUNT
      : LEGAL_CLAUSE_COMPLETENESS_OPTIONS.find((option) => option.value === payload.clauseMode)?.targetClauseCount
        ?? DEFAULT_TARGET_CLAUSE_COUNT;
  }

  if (typeof payload.targetClauseCount === "number") {
    const normalizedTarget = Math.floor(payload.targetClauseCount);
    if (Number.isFinite(normalizedTarget) && normalizedTarget > 0) {
      payload.targetClauseCount = normalizedTarget;
    } else {
      delete payload.targetClauseCount;
    }
  }

  return payload;
}

export function normalizeWarningSeverity(
  severity?: string,
): LegalWarningSeverity {
  if (severity === "critical") return "critical";
  if (severity === "warning") return "warning";
  return "info";
}
