import { ListChecks } from "lucide-react";

import { Badge } from "@/components/ui/badge";
import { sortAutoGeneratedClauses } from "@/lib/legal-contracts";
import type { AutoGenerateContractClause } from "@/types/legal-contracts";
import { cn } from "@/lib/utils";

export function SelectedClausesPanel({
  clauses,
  className,
}: {
  clauses?: AutoGenerateContractClause[];
  className?: string;
}) {
  const sorted = sortAutoGeneratedClauses(clauses ?? []);

  return (
    <section className={cn("rounded-xl border border-border/40 bg-card/30 p-4", className)}>
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <ListChecks size={16} className="text-sky-300" />
            <p className="text-sm font-semibold text-foreground">Clausulas selecionadas</p>
          </div>
          <p className="mt-1 text-xs leading-5 text-muted-foreground">
            Ordem, obrigatoriedade e risco devolvidos pela auto-geracao.
          </p>
        </div>
        <Badge variant="outline" className="border-border/40 bg-background/60 text-muted-foreground">
          {sorted.length}
        </Badge>
      </div>

      {sorted.length === 0 ? (
        <div className="mt-3 rounded-lg border border-dashed border-border/40 bg-background/50 px-4 py-3 text-sm text-muted-foreground">
          Gere o contrato inteligente para ver as clausulas selecionadas pelo backend.
        </div>
      ) : (
        <div className="mt-3 space-y-2">
          {sorted.map((clause) => (
            <article key={`${clause.id}-${clause.orderIndex}`} className="rounded-lg border border-border/40 bg-background/40 px-3 py-3">
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div className="min-w-0">
                  <p className="text-[11px] text-muted-foreground">#{clause.orderIndex + 1} {clause.slug}</p>
                  <p className="mt-1 text-sm font-medium text-foreground">{clause.title}</p>
                </div>
                <div className="flex flex-wrap gap-2">
                  <Badge variant="outline" className={clause.required ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-300" : "border-border/40 bg-background/60 text-muted-foreground"}>
                    {clause.required ? "Obrigatoria" : "Opcional"}
                  </Badge>
                  <Badge variant="outline" className="border-amber-500/30 bg-amber-500/10 text-amber-300 capitalize">
                    Risco {clause.riskLevel}
                  </Badge>
                </div>
              </div>
            </article>
          ))}
        </div>
      )}
    </section>
  );
}

