import { Badge } from "@/components/ui/badge";
import { sortAutoGeneratedClauses } from "@/lib/legal-contracts";
import type { AutoGenerateContractClause } from "@/types/legal-contracts";

type LegalClausesListProps = {
  clauses: AutoGenerateContractClause[];
  title?: string;
  emptyMessage?: string;
};

export function LegalClausesList({
  clauses,
  title = "Clausulas selecionadas",
  emptyMessage = "Nenhuma clausula selecionada pelo backend.",
}: LegalClausesListProps) {
  const sortedClauses = sortAutoGeneratedClauses(clauses);

  return (
    <section className="space-y-3">
      <div className="flex items-center justify-between gap-3">
        <div>
          <p className="text-sm font-semibold text-foreground">{title}</p>
          <p className="text-xs text-muted-foreground">
            Ordem e metadados devolvidos pela auto-geracao do backend.
          </p>
        </div>
        <Badge variant="outline" className="border-border/40 bg-background/60 text-muted-foreground">
          {sortedClauses.length}
        </Badge>
      </div>

      {sortedClauses.length === 0 ? (
        <div className="rounded-lg border border-border/40 bg-card/30 px-4 py-3 text-sm text-muted-foreground">
          {emptyMessage}
        </div>
      ) : (
        <div className="space-y-2">
          {sortedClauses.map((clause) => (
            <div
              key={`${clause.id}-${clause.orderIndex}`}
              className="rounded-lg border border-border/40 bg-card/30 px-4 py-3"
            >
              <div className="flex flex-wrap items-start justify-between gap-3">
                <div className="min-w-0 flex-1">
                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    <span>#{clause.orderIndex + 1}</span>
                    {clause.slug && <span className="truncate">{clause.slug}</span>}
                  </div>
                  <p className="mt-1 text-sm font-medium text-foreground">{clause.title}</p>
                </div>

                <div className="flex flex-wrap items-center gap-2">
                  {clause.required && (
                    <Badge variant="outline" className="border-emerald-500/30 bg-emerald-500/10 text-emerald-300">
                      Obrigatoria
                    </Badge>
                  )}
                  <Badge variant="outline" className="border-amber-500/30 bg-amber-500/10 text-amber-300 capitalize">
                    Risco {clause.riskLevel}
                  </Badge>
                </div>
              </div>
            </div>
          ))}
        </div>
      )}
    </section>
  );
}
